### ISSUE TITLE
Add "description, website, topics." to the github repo...

### ISSUE THREAD

**Issue by cherukumilli** [biztek/hipaa-npi-number-input#8]
I see the following below the Code tab for this element in github.

`No description, website, or topics provided.`

Please check some polymer elements and see how you can update this line.

**Comment by anushagadepalli** [comment]
@cherukumilli 
I don't have access to edit the description of the repository.

**Comment by cherukumilli** [comment]
@anushagadepalli 
I made you the admin. Pls try it now.

**Comment by anushagadepalli** [comment]
@cherukumilli 
I have added description, website and topics. Please review.

**Comment by cherukumilli** [comment]
LGTM
